<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Variable use and instanciation</title>
    </head>
<body>
    <p>This is a static text generated by HTML: <br />
    <?php
        $university = "UM6P";
        $school = "CS";
        echo "I study at <strong>$school</strong> in $university <br/>";
        // TEST Difference between using '' and ""
        echo 'I study at <strong>$school</strong> in $university <br />';

        echo 'I study at <strong>'.$school.'</strong> in '.$university;

        echo "<br/>";

        $number = 5;
        $number2 = "5";
        echo $number.'<br/>';
        var_dump($number);
        var_dump($number2);

        /* GLOBAL VAR */
        //var_dump($GLOBAL);
    ?>
</p>
</body>
</html>